CREATE TABLE "PaymentConfig" (
  "id"          INTEGER NOT NULL DEFAULT 1,
  "bank1Name"   TEXT NOT NULL DEFAULT 'EASTWEST BANK',
  "bank1Holder" TEXT NOT NULL DEFAULT 'JOLEO TRANSPORT',
  "bank1Account" TEXT NOT NULL DEFAULT '200048853462',
  "bank2Name"   TEXT NOT NULL DEFAULT 'BDO UNIBANK',
  "bank2Holder" TEXT NOT NULL DEFAULT 'JOLEO TRANSPORT',
  "bank2Account" TEXT NOT NULL DEFAULT '013208001304',
  "gcashHolder" TEXT NOT NULL DEFAULT 'LEOVINA SALVADOR',
  "gcashNumber" TEXT NOT NULL DEFAULT '09178305652',
  "updatedAt"   TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PaymentConfig_pkey" PRIMARY KEY ("id")
);

-- Seed the singleton row
INSERT INTO "PaymentConfig" ("id", "updatedAt") VALUES (1, CURRENT_TIMESTAMP)
  ON CONFLICT ("id") DO NOTHING;
